#string methods
name = input("enter your name  :  ")
result = len(name)
print(result)
result = name.find("n")
print(result)
result = name.rfind("n")
print(result)
result = name.capitalize()
print(result)
result = name.upper()
print(result)
result = name.lower()
print(result)
result = name.isdigit()
print(result)
result = name.isalpha()
print(result)
